In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
import seaborn as  sns
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In C:\Users\Admin\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Admin\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Admin\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\Admin\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Admin\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mpl

In [6]:

# feature selection
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import SelectPercentile
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import chi2
from sklearn.feature_selection import VarianceThreshold


# import linear model
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

# model evaluation
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score



In [3]:
df=pd.read_csv("df_reg_fe.csv") 

In [4]:
df

ODATEDW_Q_4  OSOURCE_log  TCODE_log  STATE_Q_1  ZIP_Q_4  PVASTATE_log  \
0                0     0.000000   0.693147          0        0           0.0   
1                0     0.000000   0.000000          1        1           0.0   
2                0     0.000000   0.693147          0        0           0.0   
3                0     0.000000   0.000000          0        0           0.0   
4                0     4.330733   0.000000          0        0           0.0   
...            ...          ...        ...        ...      ...           ...   
95407            1     4.110874   0.000000          0        1           0.0   
95408            0     6.356108  10.968250          0        0           0.0   
95409            0     4.276666   0.693147          0        1           0.0   
95410            0     6.188264   0.693147          1        1           0.0   
95411            0     6.795706   0.693147          0        0           0.0   

        DOB_log  NOEXCH_asi  RECP3_asi  CLUSTER_log  ...  MDMAUD_R_I  \
0      7.319865           1          1          0.0  ...           0   
1      7.867106           1          1          0.0  ...           0   
2      8.666647           1          1          0.0  ...           0   
3      6.909753           1          1          0.0  ...           0   
4      0.000000           1          1          0.0  ...           0   
...         ...         ...        ...          ...  ...         ...   
95407  0.000000           3          0          0.0  ...           0   
95408  7.550661           3          0          0.0  ...           0   
95409  0.000000           3          0          0.0  ...           0   
95410  7.179308           3          0          0.0  ...           0   
95411  7.901748           3          0          0.0  ...           0   

       MDMAUD_R_L  MDMAUD_F_1  MDMAUD_F_2  MDMAUD_F_5  MDMAUD_A_C  MDMAUD_A_L  \
0               0           0           0           0           0           0   
1               0           0           0           0           0           0   
2               0           0           0           0           0           0   
3               0           0           0           0           0           0   
4               0           0           0           0           0           0   
...           ...         ...         ...         ...         ...         ...   
95407           0           0           0           0           0           0   
95408           0           0           0           0           0           0   
95409           0           0           0           0           0           0   
95410           0           0           0           0           0           0   
95411           0           0           0           0           0           0   

       MDMAUD_A_M  MDMAUD_A_T  TARGET_D  
0               0           0       0.0  
1               0           0       0.0  
2               0           0       0.0  
3               0           0       0.0  
4               0           0       0.0  
...           ...         ...       ...  
95407           0           0       0.0  
95408           0           0       0.0  
95409           0           0       0.0  
95410           0           0       0.0  
95411           0           0     150.0  

[95412 rows x 605 columns]

In [5]:
df_copy=pd.read_csv("Train.csv") 
y_all=df_copy[['TARGET_D','TARGET_B']]
y_d=y_all['TARGET_D']
y_b=y_all['TARGET_B']
# X_new = df
# y=y_b

C:\Users\Admin\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (8,51) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [6]:
y_d=df['TARGET_D']
# X_new = df.drop(columns='TARGET_D')
X_new = df

In [7]:
X_new['TARGET_B']=y_b

In [8]:
'TARGET_B' in X_new.columns, 'TARGET_D' in X_new.columns

(True, True)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y_b, test_size=0.33, random_state=42)

In [10]:
'TARGET_B' in X_train.columns, 'TARGET_D' in X_train.columns

(True, True)

## upsamping

In [11]:
#check persent responce donatation
donat  = pd.value_counts(X_train['TARGET_B'])
print('donatation:\n', donat)
percent_positive_donat = 4843/95412*100
print('donatation percent: ', percent_positive_donat)


donatation:
 0    60716
1     3210
Name: TARGET_B, dtype: int64
donatation percent:  5.075881440489666


In [12]:
x1=X_train[X_train.TARGET_B==1]
y0=X_train[X_train.TARGET_B==0]
print(x1.shape, " ", y0.shape)

(3210, 606)   (60716, 606)


In [13]:
from sklearn.utils import resample


x1=X_train[y_b==1]
y0=X_train[y_b==0]

oversampled = resample(x1,replace=True,n_samples=26100,random_state=123) 
X_train_up_samp = pd.concat([oversampled, y0])
new_rate=pd.value_counts(X_train_up_samp['TARGET_B'])
print(new_rate)
print('now', 26100/len(X_train_up_samp)*100, '% donors respond in our new oversampled dataset')
print('Number of obs in new dataset:',len(X_train_up_samp))

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.
C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """


0    60716
1    26100
Name: TARGET_B, dtype: int64
now 30.063582749723555 % donors respond in our new oversampled dataset
Number of obs in new dataset: 86816


In [14]:
X_train=X_train_up_samp
y_train=np.ravel(X_train.TARGET_B)

In [15]:
X_train = X_train.drop(columns=['TARGET_B', 'TARGET_D'], axis = 1)
X_test = X_test.drop(columns=['TARGET_B', 'TARGET_D'], axis = 1)

In [16]:
col_test=X_test.columns
len(col_test)

604

In [17]:
'TARGET_B' in X_train.columns, 'TARGET_D' in X_train.columns

(False, False)

### Scaling

In [18]:
scaler = preprocessing.StandardScaler()
# X_scale = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test =scaler.fit_transform(X_test)

In [ ]:
#y_train = scaler.fit_transform(y_train)
#y_test =scaler.fit_transform(y_test)

In [ ]:
#X_train.to_csv(X_train_scaled_ups.csv', header = True, index = False)
#X_test.to_csv(X_test_scaled_ups.csv', header = True, index = False)
#y_train.to_csvy_train_scaled_ups.csv', header = True, index = False)
#y_test.to_csv(y_test_scaled_ups.csv', header = True, index = False)

## Clasification

In [22]:

from sklearn.neural_network import MLPClassifier  
mlpc_model=MLPClassifier(hidden_layer_sizes=(700,500,100))

In [23]:
mlpc_model.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(700, 500, 100), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [24]:
predicted = mlpc_model.predict(X_test)

In [25]:
confusion_matrix(y_test, predicted)

array([[29319,   534],
       [ 1588,    45]], dtype=int64)

In [26]:
from sklearn.metrics import f1_score
f1_sc_test=f1_score(y_test, predicted)
print('f1_sc_test:', f1_sc_test)

f1_sc_test: 0.0406871609403255


In [27]:
## SCORE CALCULATION

def score_fn():
    res_sum=0
    for index in range(X_test.shape[0]):   
        if ((predicted[index] == 1.) and (df['TARGET_B'][index] == 1) and (df['TARGET_D'][index] > 0.68)):
            res_sum += df['TARGET_D'][index] -0.68
    print('res_sum: ',res_sum)
    return res_sum
res=score_fn()
res

res_sum:  430.6399999999999


430.6399999999999

In [28]:
import pickle
# save the model to disk
filename = 'mlpcclass_model_10-04-2021.sav'
pickle.dump(mlpc_model, open(filename, 'wb'))



In [52]:
import pickle
# load the model from disk
filename = 'mlpcclass_model_10-04-2021.sav'
loaded_model = pickle.load(open(filename, 'rb'))

#### Score for test set with MLPClassifier

In [53]:
df2=pd.read_csv("ftest_df_final1.csv")

In [54]:
ydf=pd.read_csv("valtargt.txt") 
y_b=ydf['TARGET_B']
y_d=ydf['TARGET_D']

In [55]:
scaler = preprocessing.StandardScaler()
# X_scale = StandardScaler()
X_test2 =scaler.fit_transform(df2)

In [56]:
predicted = loaded_model.predict(X_test2)

In [57]:
confusion_matrix(y_b, predicted)

array([[89370,  2124],
       [ 4772,   101]], dtype=int64)

In [58]:
from sklearn.metrics import f1_score
f1_sc_test=f1_score(y_b, predicted)
print('f1_sc_test:', f1_sc_test)

f1_sc_test: 0.028458720766413072


In [59]:

## SCORE CALCULATION

def score_fn():
    res_sum=0
    for index in range(X_test2.shape[0]):   
        if ((predicted[index] == 1.) and (y_b[index] == 1) and (y_d[index] > 0.68)):
            res_sum += y_d[index] -0.68
    print('res_sum: ',res_sum)
    return res_sum
res=score_fn()
res

res_sum:  1522.3199999999993


1522.3199999999993

#### Logistic regresion

In [19]:
from sklearn import linear_model, datasets
from sklearn.feature_selection import RFECV
from sklearn.feature_selection import RFE

In [20]:
### variable reduction

# specify the model
estimator = LogisticRegression(class_weight='balanced')    # estimator for RFE, select the suitable model 


In [21]:

estimator.fit(X_train,y_train)


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
predictions = estimator.predict(X_test)

In [25]:
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

[[17158 12695]
 [  703   930]]


In [27]:
score = estimator.score(X_test, y_test)
print(score)

0.5744775455758114


####  Score for test set with LogisticRegression

In [7]:
df2=pd.read_csv("ftest_df_final1.csv")

In [8]:
ydf=pd.read_csv("valtargt.txt") 
y_b=ydf['TARGET_B']
y_d=ydf['TARGET_D']

In [44]:
scaler = preprocessing.StandardScaler()
# X_scale = StandardScaler()
X_test2 =scaler.fit_transform(df2)

In [45]:
predicted = estimator.predict(X_test2)

In [46]:
confusion_matrix(y_b, predicted)

array([[50231, 41263],
       [ 2622,  2251]], dtype=int64)

In [47]:
from sklearn.metrics import f1_score
f1_sc_test=f1_score(y_b, predicted)
print('f1_sc_test:', f1_sc_test)

f1_sc_test: 0.09304151941637218


In [48]:

## SCORE CALCULATION

def score_fn():
    res_sum=0
    for index in range(X_test2.shape[0]):   
        if ((predicted[index] == 1.) and (y_b[index] == 1) and (y_d[index] > 0.68)):
            res_sum += y_d[index] -0.68
    print('res_sum: ',res_sum)
    return res_sum
res=score_fn()
res

res_sum:  33548.94999999944


33548.94999999944

#  Score for test set if send to everyone

In [9]:
df2=pd.read_csv("ftest_df_final1.csv")

In [10]:
ydf=pd.read_csv("valtargt.txt") 
y_b=ydf['TARGET_B']
y_d=ydf['TARGET_D']

In [12]:
def score_fn():
    res_sum=0
    for index in range(df2.shape[0]):   
            res_sum += y_d[index] -0.68
    print('res_sum: ',res_sum)
    return res_sum
res=score_fn()
res

res_sum:  10560.080000000838


10560.080000000838

## Conclusion

'''In this investigation LogisticRegression winning'''

## Future goals


'''There is  many ideas to check others methods for models and feature ingenering, 
Is still missing result comparison visualisation.
Regression models.
 '''